# Configuração do Dependabot para atualizações automáticas de dependências
version: 2
updates:
  # Atualizações de dependências Python
  - package-ecosystem: "pip"
    directory: "."
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "WenFra005"
    assignees:
      - "WenFra005"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignorar atualizações de versões major (quebram compatibilidade)
      - dependency-name: "*"
        update-types: ["version-update:semver-major"] 