# Configuração do Dependabot para atualizações automáticas de dependências
version: 2
updates:
  # Atualizações de dependências Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore"
      include: "scope" 